Develop
Mamvriyskiy/bashnyaGo pull request #1
Opened 2023-10-23 05:49 UTC by Mamvriyskiy

2023-10-31 20:56 UTC, bloodNtears commented on task-3/main.go
> +			os.Exit(-1) //Negative read
Смотри, не оч круто прерывать программу посреди функции (допустим, у тебя запущены параллельные процессы, и не факт, что они успешно завершаться при таком подходе). В твоём случае логика линейная, но лучше сразу привыкать писать красиво, а то потом будет больно...

Сделай так: либо выводишь ошибку и делаешь ```return nil```, либо прокидываешь ошибку выше ```return nil, err```. В таком случае сделай возврат ошибки в функции ```([]int, error)```. Проследи, чтобы ты не печатал ошибку два раза в разных местах)

2023-10-31 20:56 UTC, bloodNtears commented on task-3/main.go
> +		fmt.Print(slice[i], " ")
если хочешь выводить по элементам - окейно, вопросов нет

если интересно, как сделать проще, [почитай](https://stackoverflow.com/a/24489454)

2023-10-31 20:56 UTC, bloodNtears commented on task-3/main.go
> +}
будет круче использовать срезы

2023-10-31 20:56 UTC, bloodNtears commented on task-4/main.go
> +		os.Exit(-2)
сообщение об ошибке хотелось бы тут

2023-10-31 20:56 UTC, bloodNtears commented on task-4/main.go
> +		}
метки значительно уменьшают читаемость кода

вместо ```break exit``` сделай ```return NO```, функция дальше не пойдёт

и в конце можешь сделать ```return "YES"```, чтоб не создавать лишнюю переменную ```result```

2023-10-31 20:56 UTC, bloodNtears commented on task-5/main.go
> +    return result
валидно, вижу твой комментик с ```strings.ReplaceAll``` - можешь юзать)

2023-10-31 20:56 UTC, bloodNtears commented on task-6/main.go
> +	for i := 0; i < len(numbers); i++ {
валидно, но можно проще ```for i, num := range numbers```

если ```i``` не нужно, то так ```for _, num := range numbers```

2023-10-31 20:56 UTC, bloodNtears commented on task-6/main.go
> +			os.Exit(-1)
писал в другом месте про это, почекай, поправь если ещё где есть

2023-10-31 20:59 UTC, bloodNtears commented
привет!

респект за оперативность, проверил, комментики оставил. если будут вопросы - пиши под комментами)

Остался вопрос: ты добавил тесты, я попробовал их позапускать, ничё не вышло: ```task-1/main_test.go:44:7: undefined: searchHypotenuse```. Как ты их запускаешь у себя?

В остальном круто! Работаем🤝

2023-10-31 22:57 UTC, Mamvriyskiy commented on task-3/main.go
> +			os.Exit(-1) //Negative read
done

2023-10-31 22:57 UTC, Mamvriyskiy commented on task-3/main.go
> +		fmt.Print(slice[i], " ")
done

2023-10-31 22:57 UTC, Mamvriyskiy commented on task-3/main.go
> +}
done

2023-10-31 22:57 UTC, Mamvriyskiy commented on task-4/main.go
> +		os.Exit(-2)
done

2023-10-31 22:58 UTC, Mamvriyskiy commented on task-4/main.go
> +		}
done

2023-10-31 22:58 UTC, Mamvriyskiy commented on task-6/main.go
> +	for i := 0; i < len(numbers); i++ {
done

2023-10-31 22:58 UTC, Mamvriyskiy commented on task-6/main.go
> +			os.Exit(-1)
done

2023-10-31 23:00 UTC, Mamvriyskiy commented
Здравствуйте. Тесты запускал, находясь в task-[1:6], go test -v -bench=.

2023-11-03 09:46 UTC, bloodNtears commented
Понял, спасибо! Запушь, пожалуйста, файл ```go.mod``` - он содержит в себе модули, которые ты используешь в проекте

2023-11-04 11:22 UTC, Yu-Leo requested changes
Привет! Присоединяюсь к ревью твоего решения :)

Для начала респект за тесты! 🔥🔥🔥

Помимо замечаний, которые я прописал отдельно к строкам, есть более общие, касающиеся тестов.
1. Не очень понял, зачем используешь `testing.B`? По-моему, тут будет достаточно обычного `testing.T`
2. Для проверки в тестах можно использовать пакет `assert` из https://github.com/stretchr/testify. Это упростит чтение тестов
3. Для того чтобы не плодить множество тестовых ф-ций с различными значенями, можно использовать table-driven testing. Можешь почитать про это [тут](https://go.dev/blog/subtests) и [тут](https://habr.com/ru/companies/otus/articles/741618/). По сути всё сводится к созданию переменной `testCases`, содержащей различные тестовые сценарии и последующей итерации по ней

2023-11-04 11:22 UTC, Yu-Leo commented on task-1/main_test.go
> +	var x float64 = 3
Можно упростить до `x := 3.0`. Аналогично с остальными переменными

2023-11-04 11:22 UTC, Yu-Leo commented on task-1/main.go
> +}
Думаю, можно использовать библиотечную ф-цию [Hypot](https://pkg.go.dev/math#Hypot)

2023-11-04 11:22 UTC, Yu-Leo commented on task-2/main.go
> +func checkTriagles(a, b, c int)  string {
1. Лишний пробел перед `string`
2. Думаю, лучше переписать код так, чтобы эта ф-ция возращала bool, а потом на основе этого возвращаемого значения выводить "YES" или "NO"

2023-11-04 11:22 UTC, Yu-Leo commented on task-4/main.go
> +func createMatrix(reader *bufio.Reader, n int) ([][]int, error) {
Если эта ф-ция **читает** матрицу, думаю, лучше назвать её `readMatrix`

2023-11-04 11:22 UTC, Yu-Leo commented on task-4/main.go
> +func checkSymmetryMatrix(matrix [][]int, n int) string {
Думаю, лучше переписать код так, чтобы эта ф-ция возращала bool, а потом на основе этого возвращаемого значения выводить "YES" или "NO"

2023-11-04 11:22 UTC, Yu-Leo commented on task-5/main.go
> +}
В конце файлов принято оставлять пустую строку

2023-11-04 11:22 UTC, Yu-Leo commented on task-6/main.go
> +	numberMap := make(map[int]int)
Можно использовать `map[int]struct{}`, поскольку нам не нужно хранить сами значения. Такой вариант будет занимать меньше памяти

2023-11-05 13:09 UTC, Mamvriyskiy commented on task-1/main_test.go
> +	var x float64 = 3
done

2023-11-05 13:09 UTC, Mamvriyskiy commented on task-1/main.go
> +}
done

2023-11-05 13:09 UTC, Mamvriyskiy commented on task-2/main.go
> +func checkTriagles(a, b, c int)  string {
done

2023-11-05 13:11 UTC, Mamvriyskiy commented on task-4/main.go
> +func createMatrix(reader *bufio.Reader, n int) ([][]int, error) {
Разбил на две функции. CreateMatrix, так как происходит создание(аллокация) матрицы, в которой вызывается readMatrix. done

2023-11-05 13:11 UTC, Mamvriyskiy commented on task-4/main.go
> +func checkSymmetryMatrix(matrix [][]int, n int) string {
done

2023-11-05 13:11 UTC, Mamvriyskiy commented on task-5/main.go
> +}
done

2023-11-05 13:11 UTC, Mamvriyskiy commented on task-6/main.go
> +	numberMap := make(map[int]int)
done

2023-11-06 09:56 UTC, bloodNtears commented on task-1/main_test.go
> +	for _, tmp := range testCases {
Небольшое замечание, обычно в тестах здесь имеется в виду не временная переменная ```tmp```, а ```tc``` - ```test case```

2023-11-06 15:38 UTC, Mamvriyskiy commented on task-1/main_test.go
> +	for _, tmp := range testCases {
done

2023-11-06 16:31 UTC, bloodNtears commented on task-1/main_test.go
> +	for _, tmp := range testCases {
поправь в каждом тестовом файле и дам апрув)

2023-11-06 16:41 UTC, Mamvriyskiy commented on task-1/main_test.go
> +	for _, tmp := range testCases {
done

2023-11-06 17:40 UTC, bloodNtears approved these changes

2023-11-06 17:40 UTC, bloodNtears commented
всё чётко, можешь мерджить)

2023-11-06 17:44 UTC, merged